### ISSUE TITLE
Centos 7 support

### ISSUE THREAD

**Issue by rockybulwinkle** [Xilinx/libsystemctlm-soc#1]
I feel like it should be mentioned in the readme about Centos 7 that it has something called "software collections library" that allows installing a newer gcc than is available by default. More here: https://wiki.centos.org/AdditionalResources/Repositories/SCL

**Comment by edgarigl** [comment]
I suppose we could add a link and a short note. We just have to be a little careful not to add too many details otherwise the document will grow and it'll be hard to see the forest through the trees...
Would you like to suggest something with a patch?
