### ISSUE TITLE
Having error running examples in tri branch

### ISSUE THREAD

**Issue by tianrui-wei** [Xilinx/libsystemctlm-soc#10]
First off, this is an extremely interesting and innovative project. Kudos to the developers!

I was trying to work on tri branch a bit more, hopefully get a bit more integration into Qemu. However, the HEAD of tri branch doesn't seem to work. [This commit](https://github.com/tianrui-wei/libsystemctlm-soc/commit/0818af61fc1407c04cca1bb2857e11d6735068f1) is a first attempt to make it work. However, there is still a ld error. The exact error message as of now is 

> eva@eva-virtual-machine:~/libsystemctlm-soc/tests/example-rtl-tri$ make
g++-10 -std=c++14 -MMD -Wall -Wno-strict-overflow -I /usr/local/share/verilator/include -Wno-strict-overflow -Wall -g -I /usr/local/systemc-2.3.2//include/ -I obj_dir -I /include -I ../../ -I ../ -I . -L /usr/local/systemc-2.3.2//lib-linux64 -Wl,-rpath,/usr/local/systemc-2.3.2//lib-linux64  obj_dir/Vsystem__ALL.a obj_dir/Vaxifull_dev__ALL.a example-rtl-tri.o obj_dir/verilated.o ../test-modules/memory.o -pthread -lsystemc -o example-rtl-tri
example-rtl-tri.o: In function `Top::Top(sc_core::sc_module_name)':
/home/eva/libsystemctlm-soc/tests/example-rtl-tri/example-rtl-tri.cc:182: undefined reference to `Vsystem::Vsystem(sc_core::sc_module_name)'
/home/eva/libsystemctlm-soc/tests/example-rtl-tri/example-rtl-tri.cc:182: undefined reference to `Vsystem::~Vsystem()'
example-rtl-tri.o: In function `Top::~Top()':
/home/eva/libsystemctlm-soc/tests/example-rtl-tri/example-rtl-tri.cc:100: undefined reference to `Vsystem::~Vsystem()'
collect2: error: ld returned 1 exit status
Makefile:72: recipe for target 'example-rtl-tri' failed
make: *** [example-rtl-tri] Error 1

There were a bunches of errors rejected by Verilator before the commit also. I was wondering if you could tell me a bit more about the state of this branch?

My environments:
OS: Ubuntu 18.04
Verilator: 4.108
System C: 2.32

**Comment by franciscoIglesias** [comment]
Hi tianrui-wei,

I updated the Makefile and also rebased on master for obtaining
the latest code in the branch at my fork, would it be possible for you to try that out
using below commands?

```
$ git clone https://github.com/franciscoIglesias/libsystemctlm-soc.git -b dev/tri
$ cd libsystemctlm-soc
$ cat <<EOF > .config.mk
SYSTEMC = /usr/local/systemc-2.3.2
EOF
$ cd tests/example-rtl-tri/
$ make
$ ./example-rtl-tri
```

My versions:

Ubuntu: 18:04
GCC version: 7.4.0 (also tried 8.3.0)
SystemC: 2.3.2
Verilator version: 4.016

Best regards,
Francisco Iglesias

**Comment by tianrui-wei** [comment]
Dear Mr.Iglesias,

Thanks for replying to my problem so quickly. I have tried your 
commands, and they work wonderfully. The problem is fixed
now!

Best wishes,
Tianrui Wei
