### ISSUE TITLE
Segmentation fault on get_posted() call

### ISSUE THREAD

**Issue by vlenoirSemtech** [Xilinx/libsystemctlm-soc#2]
When sending tlm_generic_payload through an initiator socket, a segmentation fault happens on get_posted() call. Indeed if genattr does not exist, for instance if get_extension() is not supported, the get_posted() method call is failing.

Code in remote-port-tlm-memory-slave.cc line 136 :

```
if (genattr->get_posted()) {
    return;
}
```
Problem can be fixed by testing genattr before :

```
if (genattr) {
    if (genattr->get_posted()) {
        return;
    }
}
```

**Comment by edgarigl** [comment]
Thanks, I'll commit a fix for this soon!
