### ISSUE TITLE
blocking the the whole processing thread when there is a hazard ?

### ISSUE THREAD

**Issue by gxflying** [Xilinx/libsystemctlm-soc#25]
Hi sir:
     I learned the flow of the chi inter-connect and found that the thread [RequestOrderer::req_ordering_thread](https://github.com/Xilinx/libsystemctlm-soc/blob/42aa8ed780cb9eef3a61bc50ea35ff079a7e6284/tlm-modules/iconnect-chi.h#L1864)
will be blocked when there is a hazard for a cache line(a ongoing request for a cacheline, and a incoming request for the same cache line).
but theoretically, **the request to a diffrent cache line can be handled and be processed nomally,**  but in the current implementation,  the request to a diffrent line is also blocked!   because the  [RequestOrderer::req_ordering_thread](https://github.com/Xilinx/libsystemctlm-soc/blob/42aa8ed780cb9eef3a61bc50ea35ff079a7e6284/tlm-modules/iconnect-chi.h#L1864) only be waked up when the hazard request is done.  is my understanding right ?

https://github.com/Xilinx/libsystemctlm-soc/blob/42aa8ed780cb9eef3a61bc50ea35ff079a7e6284/tlm-modules/iconnect-chi.h#L1880

**Comment by figlesia-xilinx** [comment]
Hi Felix,

The chi interconnect at the moment does not process multiple requests simultaneously/in parallel, it processes requests one by one (see lines 1894-1897). The overlapping check is there for when support for above has been introduced into the interconnect.

Best regards,
Francisco

**Comment by figlesia-xilinx** [comment]
Hi Felix,

Yes above is correct. Perhaps with the minor rephrasing on the '...should have the abilities...' to '...is allowed to have the abilities...'. Processing in parallel is done for performance and is probably always done (but it is not a must feature of an interconnect).

[iconnect-chi.h](https://github.com/Xilinx/libsystemctlm-soc/blob/42aa8ed780cb9eef3a61bc50ea35ff079a7e6284/tlm-modules/iconnect-chi.h) currently does not support this yet, but this is definitively an addition that would be great have.

Best regards,
Francisco

**Comment by gxflying** [comment]
@figlesia-xilinx , got it， Thanks ~
