### ISSUE TITLE
remote-port-tlm-memory-slave mode read and write question 

### ISSUE THREAD

**Issue by jackrong** [Xilinx/libsystemctlm-soc#3]
Hi 
     I am sorry, I have a question about slave mode' reading and writing. when muti-slave write package in same time. because we send socket package which is splitted in two. fristly, writing package header, secondly writing data. I got it from "remote-port-tlm-memory-slave.cc" line 127-130.  So I am strange about this. if A process complete sending package header of itself. but B process send it's package header in behind of A process.  After B process compete sending package header, A begin to send data. After B send it's data. So how identfy the whole A's package in QEMU receiver.  becasue the package order is disrupt.

**Comment by edgarigl** [comment]
Hi Jack,

The SystemC implementation of Remote-port relies on SystemC's voluntary preemption. The main complication with the SystemC implementation is that it needs to be reentrant in some areas.

In QEMU, the remote-port packet handling is protected by mutexes.

Cheers,
Edgar
