### ISSUE TITLE
pc-axilite.h handshakes naming error

### ISSUE THREAD

**Issue by fpi-klukomski** [Xilinx/libsystemctlm-soc#4]
There is a problem with naming of signals (duplicate of check-axilite-reset):

`		m_check_axilite_handshakes("check-axilite-reset", this),`

where it should be renamed to:

`m_check_axilite_handshakes("check-axilite-handshakes", this),`

This results in runtime warning from SystemC (2.3.2 compiled with g++9):

> Warning: (W505) object already exists: top.checker.check-axilite-reset. Latter declaration will be renamed to top.checker.check-axilite-reset_0
In file: kernel/sc_object_manager.cpp:153

**Comment by edgarigl** [comment]
Thanks, yes I noticed this the other day. It's been fixed now.
