### ISSUE TITLE
Missing ../.config.mk file

### ISSUE THREAD

**Issue by aolofsson** [Xilinx/libsystemctlm-soc#5]
The file libsystemctlm-soc/tests/Makefile makes a call to ../.config.mk, which is missing in the git repo. README does not specify adding an empty file as mandatory.

Would help on-ramp if the examples ran out of the box without the need to manually add/edit an in tree file. (file is being filtered in .gitignore)

**Comment by aolofsson** [comment]
After adding an .config.mk empty file and deleting my .local python lib (my issue!), the examples run and generate nice vcd wafeforms that make chipheads like me feel at home.:-) Very nice!

Maybe just add something like "touch .config.mk" to the README?

**Comment by edgarigl** [comment]
Thanks Andreas,

I've now made the .config.mk optional (no need to create anything unless the user needs/wants to override some default setting).

I also noticed that in recent Ubuntu, there's a libsystemc-dev package. Installing that means there're no manual installation steps needed to run the testsuite anymore. I've updated the README to reflect that.

Hope that helps!

Cheers,
Edgar

**Comment by aolofsson** [comment]
Hi Edgar,
 It was ok as it was but I am sure this will save some debug time for some new users.
Thank you for supporting the community!
Andreas
